# Generated by Django 3.1.1 on 2021-02-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=1, upload_to='img/blog/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
