# Generated by Django 3.2 on 2021-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_img', models.ImageField(upload_to='img/project', verbose_name='Главное изображение')),
                ('img2', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img3', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img4', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img5', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img6', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img7', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img8', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
                ('img9', models.ImageField(blank=True, upload_to='img/project', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
