# Generated by Django 3.2 on 2021-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_options',
            field=models.ManyToManyField(to='proposal.Options'),
        ),
    ]
