# Generated by Django 3.2 on 2021-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210611_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.TextField(default=2, verbose_name='Руководитель проекта'),
            preserve_default=False,
        ),
    ]
