# Generated by Django 3.2 on 2021-06-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='leader',
        ),
    ]
