# Generated by Django 3.2 on 2021-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дизайнер'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.CharField(blank=True, max_length=50, verbose_name='Руководитель проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='plotnik',
            field=models.CharField(blank=True, max_length=50, verbose_name='Плотник'),
        ),
    ]
