# Generated by Django 3.2 on 2021-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210611_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.CharField(blank=True, max_length=50, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='project',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
    ]
