# Generated by Django 3.2 on 2021-06-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование опции')),
                ('img', models.ImageField(upload_to='img/options', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название дерева')),
                ('img', models.ImageField(upload_to='img/wood', verbose_name='Изображение')),
                ('categories_type', models.CharField(choices=[('V', 'Вагонка'), ('P', 'Полок')], max_length=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дерево',
                'verbose_name_plural': 'Дерево',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('scale', models.CharField(blank=True, max_length=50, verbose_name='Размер помещения')),
                ('sity', models.CharField(max_length=200, verbose_name='Город')),
                ('number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Почта')),
                ('img', models.ImageField(upload_to='img/proposal', verbose_name='Изображение')),
                ('form_options', models.ManyToManyField(to='proposal.Options')),
                ('form_wood', models.ManyToManyField(to='proposal.Wood')),
            ],
            options={
                'verbose_name': 'Зявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
