# Generated by Django 3.2 on 2021-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20210611_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='village',
            field=models.CharField(default=2, max_length=100, verbose_name='Расположение объекта от города'),
            preserve_default=False,
        ),
    ]
