# Generated by Django 3.2 on 2021-05-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
                ('categories_type', models.CharField(choices=[('R', 'Готовые решения'), ('O', 'Товары под заказ')], max_length=1, verbose_name='Раздел категории')),
            ],
        ),
    ]
